### ISSUE TITLE
fix: trueno-gpu compilation errors blocking entrenar Phase 11

### ISSUE THREAD

**Issue by noahgift** [paiml/trueno#87]
## Summary

`trueno-gpu` currently fails to compile with **102 errors** when using `--features cuda`. This blocks `entrenar` Phase 11 (CUDA Migration) from using the newly implemented backward kernels.

## Reproduction

```bash
cd trueno
cargo check -p trueno-gpu --features cuda
# Result: 102 errors
```

## Error Categories

1. **Missing `use crate::kernels::Kernel` imports** in `resident/mod.rs`:
   - Methods `emit_ptx()` and `name()` not found for kernel structs
   - The `Kernel` trait is implemented but not imported in scope

2. **Type inference issues** (E0282):
   ```
   error[E0282]: type annotations needed
      --> trueno-gpu/src/memory/resident/mod.rs:502:19
      |
   502 |         let ptx = kernel.emit_ptx();
      |                   ^^^^^^ cannot infer type
   ```

3. **Duplicate definitions** in `ops.rs` (E0592):
   - `matmul`, `softmax`, `add`, `scale`, etc.

## Impact

**Blocks:**
- `entrenar` SPEC-FT-001 Phase 11 (CUDA Migration)
- Issue #85 backward kernels integration

**The backward kernels (Issue #85) have been implemented and are ready:**
- `trueno-gpu/src/kernels/backward/` exists with 8 kernels
- All 32 tests pass (when compiled in isolation)
- But the main crate won't compile, so they can't be used downstream

## Suggested Fix

1. Add missing imports:
   ```rust
   use crate::kernels::Kernel;
   ```

2. Resolve duplicate function definitions in `ops.rs`

3. Add type annotations where needed

## Priority

**P0** - This is the critical path blocker for entrenar GPU acceleration.
